version: 2
updates:
  - package-ecosystem: pip
    directory: /life-circle-assistant/backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /life-circle-assistant/frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: docker
    directory: /life-circle-assistant/backend
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /life-circle-assistant/frontend
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
